### ISSUE TITLE
como vas a persistir la referencia al turno dentro del estado?

### ISSUE THREAD

**Issue by maurociancio** [kevingadacz/Seminario#10]
https://github.com/kevingadacz/Seminario/blob/cf9a665b70b9fb8b745e07adf0875700a48b7b03/src/main/java/Modelo/Turno/Turno.java#L15

**Comment by kevingadacz** [comment]
Para persistir el estado del turno pensabamos tener una tabla de EstadoTurno y luego al persistir el turno guardar el id del estado turno correspondiente

**Comment by maurociancio** [comment]
mmmm es DEMASIADO eso.
me suena que el estado del turno alcanza con que sea un atributo de la entidad turno.
si vamos a las tablas, con que haya un campo "estado" para el turno, entiendo que alcanza re bien.


hacer una entidad para el estado es medio overkill.

tambien se puede resolver muy bien con un user type de hibernate,
aca hay un link http://benemon.blogspot.com/2012/06/hibernate-and-state-pattern-persistence.html


otra opcion es usar enums.

los enums pueden tener metodos y pueden tener parametros en los constructores.
y los enums spring boot/hibernate los persiste automaticamente sin la necesidad de escribir nada de codigo. miren esto:


enum Estado {
ABIERTO,
CERRADO,

Estado void abrir() {
 if (this == CERRADO) ABIERTO
 else throw new ....
}

Estado void cerrar() {
 if (this == ABIERTO) CERRADO
 else throw new ....
}

}

**Comment by kevingadacz** [comment]
utilizaremos un campo "estado" en la tabla Turno para guardar el estado del turno
