### ISSUE TITLE
duracion? ver clase Duration de java time

### ISSUE THREAD

**Issue by maurociancio** [kevingadacz/Seminario#13]
https://github.com/kevingadacz/Seminario/blob/cf9a665b70b9fb8b745e07adf0875700a48b7b03/src/main/java/Modelo/Servicio/Servicio.java#L7

**Comment by kevingadacz** [comment]
En cuanto a este cambio tenemos dudas por el tema de la persistencia como vamos a hacer

**Comment by maurociancio** [comment]
capaz esto les sirva? https://thorben-janssen.com/jpa-tips-map-duration-attribute/
aca otro link https://thorben-janssen.com/hibernate-enum-mappings/


seguro se puede hacer con User Type de hibernate. quizas haya algun camino mas corto

**Comment by kevingadacz** [comment]
Se cambia el tipo del atributo duracion de int a Duration
