### ISSUE TITLE
equals y hashcode de cliente (y todas entidades) se debe implementar con los atributos minimos que identifiquen a la entidad, no con todos los atributos

### ISSUE THREAD

**Issue by maurociancio** [kevingadacz/Seminario#17]
https://github.com/kevingadacz/Seminario/blob/4ce451f430fbf59a8e09a01630de09aa805efe2a/src/main/java/modelo/Cliente/Cliente.java#L106

**Comment by kevingadacz** [comment]
Se corrigió utilizando los atributos mínimos necesarios
