### ISSUE TITLE
q estas queriendo modelar con esto?

### ISSUE THREAD

**Issue by maurociancio** [kevingadacz/Seminario#21]
https://github.com/kevingadacz/Seminario/blob/4ce451f430fbf59a8e09a01630de09aa805efe2a/src/main/java/modelo/Peluqueria/Peluqueria.java#L103

q son esas 2 fechas y duraciones?
suena a que falta un value object

**Comment by kevingadacz** [comment]
Se elimino porque estaba sin uso
