### ISSUE TITLE
evitar statics, no es necesaria esa clase

### ISSUE THREAD

**Issue by maurociancio** [kevingadacz/Seminario#4]
https://github.com/kevingadacz/Seminario/blob/cf9a665b70b9fb8b745e07adf0875700a48b7b03/src/main/java/Modelo/Cliente/Cliente.java#L65

**Comment by kevingadacz** [comment]
Utilizamos el patrón Singleton para solo tener un SistemaDeTurnosPeluqueria en todo el sistema y la idea era que el sistema tenga al penalizador que tmb va a ser solo 1, como nos recomendas hacer esta parte?

**Comment by maurociancio** [comment]
veria donde conviene poner este codigo para que no haya necesidad de que exista un penalizador.
las mismas entidades deben resolverlo. penalizador no tiene nombre de entidad, suena a que estamos sacando responsabilidades de las entidades y poniendolo afuera. que es lo que NO queremos hacer con DDD.


aca pego el codigo de la clase y luego te tiro algunas opciones para que revisen:



````
    public void autorizarTurno(Cliente cliente) throws Exception {
        if (penalizacionesPorCliente.getOrDefault(cliente.getId(),new ArrayList<>()).size() > 2)
            throw new Exception("El cliente no puede solicitar un turno porque ya tiene mas de 2 penalizaciones");
    }
    public void penalizar(Turno turno) {
        if (penalizacionesPorCliente.containsKey(turno.getCliente().getId()))
            penalizacionesPorCliente.get(turno.getCliente().getId()).add(new Penalizacion(turno));
        else{
            ArrayList<Penalizacion> penalizaciones = new ArrayList<Penalizacion>();
            penalizaciones.add(new Penalizacion(turno));
            penalizacionesPorCliente.put(turno.getCliente().getId(),penalizaciones);
        }

        turno.getCliente().notificar("Haz recibido una penalizacion");
        turno.getPeluqueria().notificar("Se ha penalizado correctamente al cliente");
    }
````






ambos metodos trabajan sobre turnos o clientes. ambos casos me resultan bastante claro en que o bien el cliente debe resolver si puede pedir un turno, de esa forma podria chequear si tiene penalizaciones previa y no permitir que proceda.
y al penalizar, tambien, me suena que el turno termina penalizando al cliente, creando la entidad penalizacion o similar.
no veo necesidad de esta clase.
las entidades lo pueden resolver solitas.

**Comment by kevingadacz** [comment]
Se elimina la clase sistema y penalizador, se mueve la logica al cliente
