### ISSUE TITLE
xq no usar el id aca? si siempre esta definido y nunca cambia

### ISSUE THREAD

**Issue by maurociancio** [kevingadacz/Seminario#6]
https://github.com/kevingadacz/Seminario/blob/cf9a665b70b9fb8b745e07adf0875700a48b7b03/src/main/java/Modelo/Cliente/Cliente.java#L94

**Comment by kevingadacz** [comment]
Tanto el hashCode como el equals estamos utilizando el que se genera automaticamente dsd Intellij

**Comment by maurociancio** [comment]
esta bien que uses el idea para autogenerar cosas, pero hay que tener en claro las bases de cuando tiene sentido que sean todos los atributos y cuando no.
