### ISSUE TITLE
private?

### ISSUE THREAD

**Issue by maurociancio** [kevingadacz/Seminario#7]
https://github.com/kevingadacz/Seminario/blob/cf9a665b70b9fb8b745e07adf0875700a48b7b03/src/main/java/Modelo/Cliente/Cliente.java#L85

**Comment by kevingadacz** [comment]
Por como lo pensamos es correcto que sea publico ya que es utilizado por el Penalizador este método (la idea seria qe dsd el sistema puedas notificar a los clientes y peluquerias). Ese notificar termina pidiéndole a su formaDeNotificar que notifique el mensaje que le llego (la formaDeNotificar podria hacerlo por mail,wpp,etc).

**Comment by maurociancio** [comment]
oki, guarda con el penalizador, algo no me cierra. no tiene nombre de entidad
