### ISSUE TITLE
todas las transiciones de turnos son validas?

### ISSUE THREAD

**Issue by maurociancio** [kevingadacz/Seminario#9]
https://github.com/kevingadacz/Seminario/blob/cf9a665b70b9fb8b745e07adf0875700a48b7b03/src/main/java/Modelo/Turno/Turno.java#L51

**Comment by kevingadacz** [comment]
No, esto lo cambiamos para que el turno le pida al estadoTurno cancelar y ahi tenemos las validaciones de negocio en cuanto a las transiciones validas (de esta manera evitamos los ifs en turno para saber su estado actual y en base a eso actuar)
